openapi: 3.0.3
info:
  title: Authentication API
  description: API contracts for user authentication (login/register)
  version: 1.0.0

servers:
  - url: https://naimalcreativityai-sdd-todo-app.hf.space
    description: Production API
  - url: http://localhost:8000
    description: Local development

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      description: Create a new user account with email, name, and password
      operationId: registerUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            example:
              email: "newuser@example.com"
              name: "New User"
              password: "SecurePass123!"
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Email already registered"
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'

  /api/auth/login:
    post:
      summary: Login user
      description: Authenticate user with email and password
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            example:
              email: "user@example.com"
              password: "SecurePass123!"
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Invalid email or password"

components:
  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - name
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address (must be unique)
          example: "newuser@example.com"
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: User's display name
          example: "New User"
        password:
          type: string
          minLength: 8
          maxLength: 72
          description: "Strong password (8-72 chars, 1 number, 1 special char)"
          example: "SecurePass123!"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
          example: "user@example.com"
        password:
          type: string
          description: User's password
          example: "SecurePass123!"

    AuthResponse:
      type: object
      required:
        - access_token
        - token_type
        - user
      properties:
        access_token:
          type: string
          description: JWT access token (valid for 7 days)
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        token_type:
          type: string
          default: "bearer"
          example: "bearer"
        user:
          $ref: '#/components/schemas/UserResponse'

    UserResponse:
      type: object
      required:
        - id
        - email
        - name
        - created_at
        - updated_at
        - is_active
      properties:
        id:
          type: string
          format: uuid
          description: User's unique identifier
          example: "550e8400-e29b-41d4-a716-446655440000"
        email:
          type: string
          format: email
          description: User's email address
          example: "user@example.com"
        name:
          type: string
          description: User's display name
          example: "John Doe"
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp (UTC)
          example: "2025-12-11T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp (UTC)
          example: "2025-12-11T10:30:00Z"
        is_active:
          type: boolean
          default: true
          description: Account active status
          example: true

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: "Invalid email or password"

    ValidationErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                example: ["body", "password"]
              msg:
                type: string
                example: "Password must contain at least 1 number"
              type:
                type: string
                example: "value_error"
